### ISSUE TITLE
ktcp will not start

### ISSUE THREAD

**Issue by georgp24** [mfld-fr/elks#19]
You have to add "-serial pty" to the qemu.sh script or ktcp will not start since /dev/ttyS0 does not work.

Since your version still includes the faulty "fs/select.c" file, the command "netstat" will not work but crash with the "panic waitpt" message.

I suggest to use the fs/inode.c and fs/namei.c files from my commit as well to avoid hunting for errors unnecessarily.

**Comment by mfld-fr** [comment]
Yes, you are right, KTCP cannot start without an available serial port to perform SLIP/CSLIP.

Indeed I won't add a serial device to the QEMU configuration, because I expect KTCP to be modified to switch to Ethernet at startup, and to only require the `/dev/eth` device.

The SLIP and CSLIP protocols had value at the time of the serial modems, but now, almost all x86 embedded systems where ELKS could run have an Ethernet chip.

About the fixes in /fs, I am waiting a bit for Jody and Juan to respond to issue jbruchon#55, because despite their modifications brought some regression, they were also intended to fix some other problems (race conditions...). So I expect a best mix to go forward.

**Comment by georgp24** [comment]
I would leave "-serial pty" in as long as ktcp has not been rewritten for eth0.

As you can see from my paper, I did extensive tests with slip and qemu. At the moment this is the only way to network with the host and works quite convenient since it is all done in software. I also do not like to use a cross-over cable, but to have a virtual cross-over cable between Qemu and the host is quite handy. My plan was to support both eth0 and slip simultaneously. This way you can test routing further.

Yes, the PCs will have an ethernet chip, but not necessarily a NE2000 card. It may be RTL or Intel or whatever - and PCI. So the NE2000 can usually only be used with Qemu too.

You can replace the three files with the versions Jody and Juan may come up with any time. But at the moment this will slow the development waiting for them to do it. I think one should base the development on a platform that works even if improvements are pending. At least I will.

**Comment by mfld-fr** [comment]
After a bit of thinking, I revised my opinion. Almost all embedded systems **do have** a serial port (typically a 3-wire TTL), not used for networking, but for debugging, especially on headless systems. So I will finally add the missing option as suggested.

**Comment by georgp24** [comment]
Hello Marc-Francois,

I began to modify ktcp. If you start it with “ktcp <ip-address> /dev/eth” it will use the eth driver instead of slip. Also changed the rc.sysinit script for that so you can start ktcp using /dev/eth when booting.

Regards

Georg

**Comment by mfld-fr** [comment]
Nice to see you are making progress on `ktcp` part ! But please, for better project tracking, try to not mix the topics, and continue the discussion about serial / ethernet switch in the right issue : https://github.com/mfld-fr/elks/issues/10.
